### ISSUE TITLE
Allow for environment variable override of configuration

### ISSUE THREAD

**Issue by kwisath** [xatkit-bot-platform/xatkit-runtime#245]
Could we make a default behavior that configurator looks first at an equivalent env variable before actually looking into the configuration file? Transformation is easy: capitalize and convert . into _ , so that xatkit.some.property looks for XATKIT_SOME_PROPERTY env var. It is very handy to allow this flexibility, especially on docker.

**Comment by gdaniel** [comment]
See https://github.com/xatkit-bot-platform/xatkit-runtime/wiki/Xatkit-Options for more information on environment variable names vs. property keys
